name = "trivio-multiplayer"
main = "worker/src/index.js"
compatibility_date = "2025-05-28"
account_id = "b987a5cb22f6fc7ba324e66d2602cc23"   

workers_dev = true

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[build]
command = "npm install"
